# **1. Data Collection**

In [209]:
# Import library untuk menampilkan dataframe
import pandas as pd

* Dataset Ulasan Produk Terminal Listrik Kategori Elektronik

In [210]:
# Membaca dataset
elektronik = pd.read_csv("E:/STT Terpadu Nurul Fikri/Semester 4/Natural Leanguage Processing/Project_Natural_Language_Processing/Data/Elektronik_Terminal.csv")

# Menampilkan 10 baris pertama
elektronik.head(10)

,Pengguna,Waktu,Ulasan
0,c*****3,"2023-04-04 18:38 | Variasi: SC-735,5 METER",Barang sesuai deskripsi & berfungsi dgn baik. Panjang kabel 5 meter & slot 5 colokan. Build quality sih keliatannya cukup baik. Semoga awet & safety. Seller jg gercep pengemasan cepat. Terima kasih.
1,b*****i,"2023-07-29 15:38 | Variasi: SC-735,10 METER, SC-735,5 METER",Hai..Barang nya sdh sampai 🤗\nProduk Original ✨\nKualitas & harga produk sangat baik 👌🏻\nKecepatan pengiriman sangat baik 🏃🏻‍♀️\nRespon penjual sangat baik 😊\nPacking aman 📦\nVariasi & ukuran sesuai pesanan 👍🏻\nBlm dicoba tp semoga bisa berfungsi dgn baik 🤲🏻\nTerima kasih 🙏🏻
2,t*****h,"2023-07-11 13:13 | Variasi: SC-733,3 METER",Super cepet gpl mantap lumayan barangnya
3,j*****n,"2023-06-07 06:13 | Variasi: SC-734,3 METER","Produknya sangat bagus, harganya juga sangat terjangkau lebih murah di toko offline, tidak ada kendala sama sekali, pengirimannya juga cepat 2 hari sampai. pokonya the best lah, worth it banget"
4,m*****y,"2024-03-09 08:37 | Variasi: SC-733,5 METER",Pengirimannya juga cepat sekali!!
5,NaN,"2024-04-13 16:06 | Variasi: SC-733,10 METER","Alhamdulilah barang nya udah yampe, barang nya mantap betul gan, sukses terus seler ama shopee Amiin 🤲"
6,s*****a,"2023-07-21 16:03 | Variasi: SC-734,10 METER","Sempat khawatir barang terlambat sampai tapi syukurnya diantar tepat waktu dan packaging aman (rapih), admin.nya good.respon juga. Barangnya bagus sesuai pesanan dan bisa dipakai juga, ngada yg.kurang dll. Terimakasih buat kurir krn sudh mau.antar pesanannya tepat waktu kurir. Semoga barang awet dan lancar rezekinya dan semuanyaa. Maaf juga baru sempat beri feedback. So, Thankyouu.."
7,NaN,"2025-05-28 16:06 | Variasi: SC-733,5 METER","Pengiriman cepat,, alat berfungsi dengan baik.puass dehh,, mudah mudahan tambah lancar jualan nya"
8,d*****d,"2025-04-20 14:10 | Variasi: SC-732,5 METER",Semoga tahan lama dan dapat digunakan dengan maksimal
9,c*****_,"2025-03-24 12:42 | Variasi: SC-734,3 METER","Worth it dengan harga segini, apalagi kl awet sampe tahunan."

In [211]:
# Menambahkan kolom 'Kategori' dengan isi 'Elektronik' untuk semua baris
elektronik['Kategori'] = 'Elektronik'

elektronik.head(10)

,Pengguna,Waktu,Ulasan,Kategori
0,c*****3,"2023-04-04 18:38 | Variasi: SC-735,5 METER",Barang sesuai deskripsi & berfungsi dgn baik. Panjang kabel 5 meter & slot 5 colokan. Build quality sih keliatannya cukup baik. Semoga awet & safety. Seller jg gercep pengemasan cepat. Terima kasih.,Elektronik
1,b*****i,"2023-07-29 15:38 | Variasi: SC-735,10 METER, SC-735,5 METER",Hai..Barang nya sdh sampai 🤗\nProduk Original ✨\nKualitas & harga produk sangat baik 👌🏻\nKecepatan pengiriman sangat baik 🏃🏻‍♀️\nRespon penjual sangat baik 😊\nPacking aman 📦\nVariasi & ukuran sesuai pesanan 👍🏻\nBlm dicoba tp semoga bisa berfungsi dgn baik 🤲🏻\nTerima kasih 🙏🏻,Elektronik
2,t*****h,"2023-07-11 13:13 | Variasi: SC-733,3 METER",Super cepet gpl mantap lumayan barangnya,Elektronik
3,j*****n,"2023-06-07 06:13 | Variasi: SC-734,3 METER","Produknya sangat bagus, harganya juga sangat terjangkau lebih murah di toko offline, tidak ada kendala sama sekali, pengirimannya juga cepat 2 hari sampai. pokonya the best lah, worth it banget",Elektronik
4,m*****y,"2024-03-09 08:37 | Variasi: SC-733,5 METER",Pengirimannya juga cepat sekali!!,Elektronik
5,NaN,"2024-04-13 16:06 | Variasi: SC-733,10 METER","Alhamdulilah barang nya udah yampe, barang nya mantap betul gan, sukses terus seler ama shopee Amiin 🤲",Elektronik
6,s*****a,"2023-07-21 16:03 | Variasi: SC-734,10 METER","Sempat khawatir barang terlambat sampai tapi syukurnya diantar tepat waktu dan packaging aman (rapih), admin.nya good.respon juga. Barangnya bagus sesuai pesanan dan bisa dipakai juga, ngada yg.kurang dll. Terimakasih buat kurir krn sudh mau.antar pesanannya tepat waktu kurir. Semoga barang awet dan lancar rezekinya dan semuanyaa. Maaf juga baru sempat beri feedback. So, Thankyouu..",Elektronik
7,NaN,"2025-05-28 16:06 | Variasi: SC-733,5 METER","Pengiriman cepat,, alat berfungsi dengan baik.puass dehh,, mudah mudahan tambah lancar jualan nya",Elektronik
8,d*****d,"2025-04-20 14:10 | Variasi: SC-732,5 METER",Semoga tahan lama dan dapat digunakan dengan maksimal,Elektronik
9,c*****_,"2025-03-24 12:42 | Variasi: SC-734,3 METER","Worth it dengan harga segini, apalagi kl awet sampe tahunan.",Elektronik

In [212]:
elektronik_clean = elektronik[["Kategori", "Ulasan"]]

elektronik_clean.head(10)

,Kategori,Ulasan
0,Elektronik,Barang sesuai deskripsi & berfungsi dgn baik. Panjang kabel 5 meter & slot 5 colokan. Build quality sih keliatannya cukup baik. Semoga awet & safety. Seller jg gercep pengemasan cepat. Terima kasih.
1,Elektronik,Hai..Barang nya sdh sampai 🤗\nProduk Original ✨\nKualitas & harga produk sangat baik 👌🏻\nKecepatan pengiriman sangat baik 🏃🏻‍♀️\nRespon penjual sangat baik 😊\nPacking aman 📦\nVariasi & ukuran sesuai pesanan 👍🏻\nBlm dicoba tp semoga bisa berfungsi dgn baik 🤲🏻\nTerima kasih 🙏🏻
2,Elektronik,Super cepet gpl mantap lumayan barangnya
3,Elektronik,"Produknya sangat bagus, harganya juga sangat terjangkau lebih murah di toko offline, tidak ada kendala sama sekali, pengirimannya juga cepat 2 hari sampai. pokonya the best lah, worth it banget"
4,Elektronik,Pengirimannya juga cepat sekali!!
5,Elektronik,"Alhamdulilah barang nya udah yampe, barang nya mantap betul gan, sukses terus seler ama shopee Amiin 🤲"
6,Elektronik,"Sempat khawatir barang terlambat sampai tapi syukurnya diantar tepat waktu dan packaging aman (rapih), admin.nya good.respon juga. Barangnya bagus sesuai pesanan dan bisa dipakai juga, ngada yg.kurang dll. Terimakasih buat kurir krn sudh mau.antar pesanannya tepat waktu kurir. Semoga barang awet dan lancar rezekinya dan semuanyaa. Maaf juga baru sempat beri feedback. So, Thankyouu.."
7,Elektronik,"Pengiriman cepat,, alat berfungsi dengan baik.puass dehh,, mudah mudahan tambah lancar jualan nya"
8,Elektronik,Semoga tahan lama dan dapat digunakan dengan maksimal
9,Elektronik,"Worth it dengan harga segini, apalagi kl awet sampe tahunan."

* Dataset Ulasan Produk Serum Kategori Kecantikan

In [213]:
# Membaca dataset
kecantikan = pd.read_csv("E:/STT Terpadu Nurul Fikri/Semester 4/Natural Leanguage Processing/Project_Natural_Language_Processing/Data/Kecantikan_Serum.csv")

# Menampilkan 10 baris pertama
kecantikan.head(10)

,Pengguna,Waktu,Ulasan,jtmC98,T79_5U,rFzVcr,QSiE2A
0,lidyatan26,2021-04-08 20:22,"Recomend teman, katanya bisa bikin kulit kenyal dan menghilangkan flex jd nyoba dl aja...semoga cocok. Pengiriman tepat waktu.. barang sesuai, tidak ada yg pecah, exp date msh lama. Thx seller",NaN,NaN,NaN,NaN
1,berkaholshop89,2022-07-04 17:53,Kulit wajah terasa lembab bersih dan halus \nRecomended bgt produkny olay\nSo coba dech \nBiar kamu tau bedany pakai facial.foam olay,|,Langganan,NaN,NaN
2,NaN,2021-07-10 20:18,Produk ORI;\nHarga murah krn beli saat SALE 😁 ;\nPacking rapi dan di bubble wrap;\nED masih lama di tahun 2024;\nPengiriman cepat.,NaN,NaN,NaN,NaN
3,NaN,2021-10-05 09:39,Cocok bgt dikulit aku yg sensitif parah dan ini kali kedua belanja disini dan bakal jadi langganan pengiriman super cepat hari ini CO hari ini jg langsung dikirim,|,Langganan,NaN,NaN
4,niniratnawaty,2020-03-17 09:20,"Olay total effects anti aging kualitas nya bgs👍🤩💖face bersih bebas minyak,nice price👍😍💖🤩 Recommended to buy.Di foto ini Ada BIOGLASS mci utk m'hslkan AIR OKSIGEN O2 HEXAGONAL 👍air yg sgt berkualitas&byk manfaat bagi tubuh utk m'buang toksin,terlbh jaman now yg rawan virus.",|,Langganan,NaN,NaN
5,meliawati64,2021-04-05 19:08,"Oley total effects, ini bermanfaat membersihkan kulit muka, sehingga bersinar & awet muda. Pengiriman cpt, respon ramah. Terima ksh penjual & pihak shopee...bener2 barang original....sukses ya....👍👍👍😁",|,Langganan,NaN,NaN
6,mamaharkana,2021-04-26 14:16,Barang sudah sampai dengan selamat. Barang yang datang sesuai dengan pesanan dan yang ada di gambar. Respon penjual dan pengiriman juga cepat.\nTerima kasih...,NaN,NaN,NaN,NaN
7,NaN,2022-01-03 15:26,Paket sdh datang dgn cepat dan dikemas dgn baik . Dan barang dlm keadaan baik jg .. terima kasih seller dan shopee ...,NaN,NaN,NaN,NaN
8,suhermen06,2023-01-06 13:19,Pengiriman tepat waktu\nKurir baik dan ramah\nIni sudah ke 7 kalinya aku pesan di sini\nAmanah tokonya\nNext order lagi di sini\nTerimakasih shopee,NaN,NaN,NaN,NaN
9,NaN,2021-04-15 11:00,Olay official emang ok bagus produk nya original udah lama pakai olay dari jaman muda belia sekarang sudah ada official store di shoppee ga usah repot ke toko beli offline,|,Langganan,NaN,NaN

In [214]:
# Menambahkan kolom 'Kategori' dengan isi 'Kecantikan' untuk semua baris
kecantikan['Kategori'] = 'Kecantikan'

kecantikan.head(10)

,Pengguna,Waktu,Ulasan,jtmC98,T79_5U,rFzVcr,QSiE2A,Kategori
0,lidyatan26,2021-04-08 20:22,"Recomend teman, katanya bisa bikin kulit kenyal dan menghilangkan flex jd nyoba dl aja...semoga cocok. Pengiriman tepat waktu.. barang sesuai, tidak ada yg pecah, exp date msh lama. Thx seller",NaN,NaN,NaN,NaN,Kecantikan
1,berkaholshop89,2022-07-04 17:53,Kulit wajah terasa lembab bersih dan halus \nRecomended bgt produkny olay\nSo coba dech \nBiar kamu tau bedany pakai facial.foam olay,|,Langganan,NaN,NaN,Kecantikan
2,NaN,2021-07-10 20:18,Produk ORI;\nHarga murah krn beli saat SALE 😁 ;\nPacking rapi dan di bubble wrap;\nED masih lama di tahun 2024;\nPengiriman cepat.,NaN,NaN,NaN,NaN,Kecantikan
3,NaN,2021-10-05 09:39,Cocok bgt dikulit aku yg sensitif parah dan ini kali kedua belanja disini dan bakal jadi langganan pengiriman super cepat hari ini CO hari ini jg langsung dikirim,|,Langganan,NaN,NaN,Kecantikan
4,niniratnawaty,2020-03-17 09:20,"Olay total effects anti aging kualitas nya bgs👍🤩💖face bersih bebas minyak,nice price👍😍💖🤩 Recommended to buy.Di foto ini Ada BIOGLASS mci utk m'hslkan AIR OKSIGEN O2 HEXAGONAL 👍air yg sgt berkualitas&byk manfaat bagi tubuh utk m'buang toksin,terlbh jaman now yg rawan virus.",|,Langganan,NaN,NaN,Kecantikan
5,meliawati64,2021-04-05 19:08,"Oley total effects, ini bermanfaat membersihkan kulit muka, sehingga bersinar & awet muda. Pengiriman cpt, respon ramah. Terima ksh penjual & pihak shopee...bener2 barang original....sukses ya....👍👍👍😁",|,Langganan,NaN,NaN,Kecantikan
6,mamaharkana,2021-04-26 14:16,Barang sudah sampai dengan selamat. Barang yang datang sesuai dengan pesanan dan yang ada di gambar. Respon penjual dan pengiriman juga cepat.\nTerima kasih...,NaN,NaN,NaN,NaN,Kecantikan
7,NaN,2022-01-03 15:26,Paket sdh datang dgn cepat dan dikemas dgn baik . Dan barang dlm keadaan baik jg .. terima kasih seller dan shopee ...,NaN,NaN,NaN,NaN,Kecantikan
8,suhermen06,2023-01-06 13:19,Pengiriman tepat waktu\nKurir baik dan ramah\nIni sudah ke 7 kalinya aku pesan di sini\nAmanah tokonya\nNext order lagi di sini\nTerimakasih shopee,NaN,NaN,NaN,NaN,Kecantikan
9,NaN,2021-04-15 11:00,Olay official emang ok bagus produk nya original udah lama pakai olay dari jaman muda belia sekarang sudah ada official store di shoppee ga usah repot ke toko beli offline,|,Langganan,NaN,NaN,Kecantikan

In [215]:
kecantikan_clean = kecantikan[["Kategori", "Ulasan"]]

kecantikan_clean.head(10)

,Kategori,Ulasan
0,Kecantikan,"Recomend teman, katanya bisa bikin kulit kenyal dan menghilangkan flex jd nyoba dl aja...semoga cocok. Pengiriman tepat waktu.. barang sesuai, tidak ada yg pecah, exp date msh lama. Thx seller"
1,Kecantikan,Kulit wajah terasa lembab bersih dan halus \nRecomended bgt produkny olay\nSo coba dech \nBiar kamu tau bedany pakai facial.foam olay
2,Kecantikan,Produk ORI;\nHarga murah krn beli saat SALE 😁 ;\nPacking rapi dan di bubble wrap;\nED masih lama di tahun 2024;\nPengiriman cepat.
3,Kecantikan,Cocok bgt dikulit aku yg sensitif parah dan ini kali kedua belanja disini dan bakal jadi langganan pengiriman super cepat hari ini CO hari ini jg langsung dikirim
4,Kecantikan,"Olay total effects anti aging kualitas nya bgs👍🤩💖face bersih bebas minyak,nice price👍😍💖🤩 Recommended to buy.Di foto ini Ada BIOGLASS mci utk m'hslkan AIR OKSIGEN O2 HEXAGONAL 👍air yg sgt berkualitas&byk manfaat bagi tubuh utk m'buang toksin,terlbh jaman now yg rawan virus."
5,Kecantikan,"Oley total effects, ini bermanfaat membersihkan kulit muka, sehingga bersinar & awet muda. Pengiriman cpt, respon ramah. Terima ksh penjual & pihak shopee...bener2 barang original....sukses ya....👍👍👍😁"
6,Kecantikan,Barang sudah sampai dengan selamat. Barang yang datang sesuai dengan pesanan dan yang ada di gambar. Respon penjual dan pengiriman juga cepat.\nTerima kasih...
7,Kecantikan,Paket sdh datang dgn cepat dan dikemas dgn baik . Dan barang dlm keadaan baik jg .. terima kasih seller dan shopee ...
8,Kecantikan,Pengiriman tepat waktu\nKurir baik dan ramah\nIni sudah ke 7 kalinya aku pesan di sini\nAmanah tokonya\nNext order lagi di sini\nTerimakasih shopee
9,Kecantikan,Olay official emang ok bagus produk nya original udah lama pakai olay dari jaman muda belia sekarang sudah ada official store di shoppee ga usah repot ke toko beli offline

* Dataset Ulasan Produk Helm Kategori Otomotif

In [216]:
# Membaca dataset
otomotif = pd.read_csv("E:/STT Terpadu Nurul Fikri/Semester 4/Natural Leanguage Processing/Project_Natural_Language_Processing/Data/Otomotif_Helm.csv")

# Menampilkan 10 baris pertama
otomotif.head(10)

,Waktu,Ulasan,Pengguna,jtmC98,T79_5U,HcSdrS src (6),HcSdrS src (7),HcSdrS src (8)
0,"2021-12-14 17:51 | Variasi: Hijau Armi dop,L (59-60)","Barang bagus, packing juga bagus pake kardus, Alhamdulillah hanya ada lecet sedikit tp aman lah, pengiriman jg cpt",NaN,NaN,NaN,NaN,NaN,NaN
1,"2023-02-27 21:35 | Variasi: Hitam kilap,XL (61-62)",Desain nya baik & pas di kepala. Memiliki double visor terutama jika kondisi perjalanan melawan arah sinar matahari dapat digunakan kacamata hitamnya. Standar SNI sehingga aman digunakan. Respon penjual baik dan waktu pengiriman tepat waktu sehingga dapat langsung dipakai. Tengkiu.,andri_irawan210382,NaN,NaN,NaN,NaN,NaN
2,"2023-01-30 16:02 | Variasi: Hijau Armi dop,L (59-60)","Rekomendasi banget, harga murah, tampilan yahut",ok2bi30l9p,NaN,NaN,NaN,NaN,NaN
3,"2023-12-15 11:23 | Variasi: Hitam kilap,M (57-58)",Barang dtg dengan selamat... semuanya oke.. tokonya amanah..packing aman dilapisi bubble crap dan kardus yg tebal.. makasih 🙏🏻 ya sudah menjadi toko yg amanah dan teliti...nanti saya mau cari helm untuk cewek di toko ini...cuma gak tau ad atau gak...,adillahmaryati,NaN,NaN,NaN,NaN,NaN
4,"2023-01-28 06:56 | Variasi: Abu abu dop,XL (61-62)","Thank you seller sudah amanah, Tanpa Chat ke seller sebenarnya, tapi minta warna Abu Abu dop langsung dikirim sesuai keinginan😁 dan juga pengiriman sangat cepat, kurir sangat ramah dan baik. Harga murah tapi bukan murahan, pokoknya mah gak nyesel beli disini. Recomended bagi yang mau cari helm disini. Murah kualitas sangat bagus. ⭐5 untuk seller dan kurir👍🏼👍🏼👍🏼",khairul_ramadani,NaN,NaN,NaN,NaN,NaN
5,"2024-11-30 14:07 | Variasi: Abu abu dop,M (57-58)","Telah sampai sesuai dengan pesanan, model bgus,enteng, warna keren gold doff, ternyata sekeren ini, pengiriman cepat dari Sidoharjo Jatim ke Lampung Utara, lngsung dipake sama temen saya yg pesen, trimakasih seller 😎👍🔥",NaN,NaN,NaN,NaN,NaN,NaN
6,"2024-12-24 14:28 | Variasi: Putih,L (59-60)","Helm nya keren dan sesuai ekspe😍\nSellernya amanah banget, bintang 5 ⭐⭐⭐⭐⭐ deh buat tokonya. Gak nyesel beli helm disini",NaN,NaN,NaN,NaN,NaN,NaN
7,"2023-04-02 05:34 | Variasi: Putih,L (59-60)","Barang sudah sampai dengan selamat,helm warna putih dengan warna sesuai pesanan.semoga cocok untuk saya,dan bisa awet.dengan harga yang sangat minim sudah dapat helm INK yang sangat berkualitas. Terimakasih kak",xfruvt3u89,NaN,NaN,NaN,NaN,NaN
8,"2024-06-09 15:17 | Variasi: Hitam dop,L (59-60)",Maaf baru kasih nilai... keren helm nya sesuai harga nyaman di pake nya warna hitam doof... Makasih seler mksh abang kurir semoga semua tambah berkah yaa,fajarul1972,NaN,NaN,NaN,NaN,NaN
9,"2024-05-22 15:00 | Variasi: Merah maron,M (57-58)","Oke kk... Paket #HELM INK DOUBLE KACA udh sya terima dgn aman& sesuai poto/ deskripsi, moga aja HELM INKnya nyaman digunakan dan safety dgn baik tentunya. 👍 Thx #NIZAMHELMETGRESIK",NaN,NaN,NaN,NaN,NaN,NaN

In [217]:
# Menambahkan kolom 'Kategori' dengan isi 'otomotif' untuk semua baris
otomotif['Kategori'] = 'Otomotif'

otomotif.head(10)

,Waktu,Ulasan,Pengguna,jtmC98,T79_5U,HcSdrS src (6),HcSdrS src (7),HcSdrS src (8),Kategori
0,"2021-12-14 17:51 | Variasi: Hijau Armi dop,L (59-60)","Barang bagus, packing juga bagus pake kardus, Alhamdulillah hanya ada lecet sedikit tp aman lah, pengiriman jg cpt",NaN,NaN,NaN,NaN,NaN,NaN,Otomotif
1,"2023-02-27 21:35 | Variasi: Hitam kilap,XL (61-62)",Desain nya baik & pas di kepala. Memiliki double visor terutama jika kondisi perjalanan melawan arah sinar matahari dapat digunakan kacamata hitamnya. Standar SNI sehingga aman digunakan. Respon penjual baik dan waktu pengiriman tepat waktu sehingga dapat langsung dipakai. Tengkiu.,andri_irawan210382,NaN,NaN,NaN,NaN,NaN,Otomotif
2,"2023-01-30 16:02 | Variasi: Hijau Armi dop,L (59-60)","Rekomendasi banget, harga murah, tampilan yahut",ok2bi30l9p,NaN,NaN,NaN,NaN,NaN,Otomotif
3,"2023-12-15 11:23 | Variasi: Hitam kilap,M (57-58)",Barang dtg dengan selamat... semuanya oke.. tokonya amanah..packing aman dilapisi bubble crap dan kardus yg tebal.. makasih 🙏🏻 ya sudah menjadi toko yg amanah dan teliti...nanti saya mau cari helm untuk cewek di toko ini...cuma gak tau ad atau gak...,adillahmaryati,NaN,NaN,NaN,NaN,NaN,Otomotif
4,"2023-01-28 06:56 | Variasi: Abu abu dop,XL (61-62)","Thank you seller sudah amanah, Tanpa Chat ke seller sebenarnya, tapi minta warna Abu Abu dop langsung dikirim sesuai keinginan😁 dan juga pengiriman sangat cepat, kurir sangat ramah dan baik. Harga murah tapi bukan murahan, pokoknya mah gak nyesel beli disini. Recomended bagi yang mau cari helm disini. Murah kualitas sangat bagus. ⭐5 untuk seller dan kurir👍🏼👍🏼👍🏼",khairul_ramadani,NaN,NaN,NaN,NaN,NaN,Otomotif
5,"2024-11-30 14:07 | Variasi: Abu abu dop,M (57-58)","Telah sampai sesuai dengan pesanan, model bgus,enteng, warna keren gold doff, ternyata sekeren ini, pengiriman cepat dari Sidoharjo Jatim ke Lampung Utara, lngsung dipake sama temen saya yg pesen, trimakasih seller 😎👍🔥",NaN,NaN,NaN,NaN,NaN,NaN,Otomotif
6,"2024-12-24 14:28 | Variasi: Putih,L (59-60)","Helm nya keren dan sesuai ekspe😍\nSellernya amanah banget, bintang 5 ⭐⭐⭐⭐⭐ deh buat tokonya. Gak nyesel beli helm disini",NaN,NaN,NaN,NaN,NaN,NaN,Otomotif
7,"2023-04-02 05:34 | Variasi: Putih,L (59-60)","Barang sudah sampai dengan selamat,helm warna putih dengan warna sesuai pesanan.semoga cocok untuk saya,dan bisa awet.dengan harga yang sangat minim sudah dapat helm INK yang sangat berkualitas. Terimakasih kak",xfruvt3u89,NaN,NaN,NaN,NaN,NaN,Otomotif
8,"2024-06-09 15:17 | Variasi: Hitam dop,L (59-60)",Maaf baru kasih nilai... keren helm nya sesuai harga nyaman di pake nya warna hitam doof... Makasih seler mksh abang kurir semoga semua tambah berkah yaa,fajarul1972,NaN,NaN,NaN,NaN,NaN,Otomotif
9,"2024-05-22 15:00 | Variasi: Merah maron,M (57-58)","Oke kk... Paket #HELM INK DOUBLE KACA udh sya terima dgn aman& sesuai poto/ deskripsi, moga aja HELM INKnya nyaman digunakan dan safety dgn baik tentunya. 👍 Thx #NIZAMHELMETGRESIK",NaN,NaN,NaN,NaN,NaN,NaN,Otomotif

In [218]:
otomotif_clean = otomotif[["Kategori", "Ulasan"]]

otomotif_clean.head(10)

,Kategori,Ulasan
0,Otomotif,"Barang bagus, packing juga bagus pake kardus, Alhamdulillah hanya ada lecet sedikit tp aman lah, pengiriman jg cpt"
1,Otomotif,Desain nya baik & pas di kepala. Memiliki double visor terutama jika kondisi perjalanan melawan arah sinar matahari dapat digunakan kacamata hitamnya. Standar SNI sehingga aman digunakan. Respon penjual baik dan waktu pengiriman tepat waktu sehingga dapat langsung dipakai. Tengkiu.
2,Otomotif,"Rekomendasi banget, harga murah, tampilan yahut"
3,Otomotif,Barang dtg dengan selamat... semuanya oke.. tokonya amanah..packing aman dilapisi bubble crap dan kardus yg tebal.. makasih 🙏🏻 ya sudah menjadi toko yg amanah dan teliti...nanti saya mau cari helm untuk cewek di toko ini...cuma gak tau ad atau gak...
4,Otomotif,"Thank you seller sudah amanah, Tanpa Chat ke seller sebenarnya, tapi minta warna Abu Abu dop langsung dikirim sesuai keinginan😁 dan juga pengiriman sangat cepat, kurir sangat ramah dan baik. Harga murah tapi bukan murahan, pokoknya mah gak nyesel beli disini. Recomended bagi yang mau cari helm disini. Murah kualitas sangat bagus. ⭐5 untuk seller dan kurir👍🏼👍🏼👍🏼"
5,Otomotif,"Telah sampai sesuai dengan pesanan, model bgus,enteng, warna keren gold doff, ternyata sekeren ini, pengiriman cepat dari Sidoharjo Jatim ke Lampung Utara, lngsung dipake sama temen saya yg pesen, trimakasih seller 😎👍🔥"
6,Otomotif,"Helm nya keren dan sesuai ekspe😍\nSellernya amanah banget, bintang 5 ⭐⭐⭐⭐⭐ deh buat tokonya. Gak nyesel beli helm disini"
7,Otomotif,"Barang sudah sampai dengan selamat,helm warna putih dengan warna sesuai pesanan.semoga cocok untuk saya,dan bisa awet.dengan harga yang sangat minim sudah dapat helm INK yang sangat berkualitas. Terimakasih kak"
8,Otomotif,Maaf baru kasih nilai... keren helm nya sesuai harga nyaman di pake nya warna hitam doof... Makasih seler mksh abang kurir semoga semua tambah berkah yaa
9,Otomotif,"Oke kk... Paket #HELM INK DOUBLE KACA udh sya terima dgn aman& sesuai poto/ deskripsi, moga aja HELM INKnya nyaman digunakan dan safety dgn baik tentunya. 👍 Thx #NIZAMHELMETGRESIK"

* Dataset Ulasan Produk Cilok Kategori Makanan

In [219]:
# Membaca dataset
makanan = pd.read_csv("E:/STT Terpadu Nurul Fikri/Semester 4/Natural Leanguage Processing/Project_Natural_Language_Processing/Data/Makanan_Cilok.csv")

# Menampilkan 10 baris pertama
makanan.head(10)

,Pengguna,Waktu,Ulasan
0,t*****2,"2023-01-29 19:15 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih","Klo soal rasa cilok nya enak tektur'a lembut gurih gak kerasa pesen dapet yg isi'a gaji, klo dari segi packing sma pengiriman standar lah yah karna kan jauh di luar kota bogor"
1,NaN,"2024-09-12 22:38 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih","Datang sesuai pesanan, cilok gajih sapi ukuran sedang isi 50 butir. Rasanya enak, ada isian gajih didalam ciloknya. Aroma sedap dan gurih. \n\nCiloknya dikirim dengan kondisi di vacuum, jadi aman sampai ke tangan konsumen. Gak basi"
2,r*****0,"2024-11-04 22:40 | Variasi: Isi 100 Uk. Mini,Keju","Endul ciloknya udah sampai walau menunggu agak lama tapi pas sampai langsung dicobain mantul enak empuk kenyal nya pas gurih tinggal di kreasikan dengan bumbu kacang atau di buat cilok kuah seblak, next order lgi"
3,NaN,"2024-09-02 12:14 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih, Isi 50 Uk. Mini,Sinti","Belum dicoba soalnya baru dateng ,dari bentuk dan rupa sih oke \nAku pikir dapet bumbu kacang nya terpisah taunya cilok isi bumbu kacang 🤣 ,salah aku sih ngga teliti tapi mudah²an rasanya enak siapa tau bisa jadi langganan ,selernya ramah responnya cepet thanks seler 👌"
4,w*****u,"2024-11-11 08:05 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih","Ciloknya diterima dalam keadaan baik,divacum dan dipacking kardus.\nTekstur kenyalnya pas,ga alot,bentuknya juga besar2 yaaa..makan 5pcs sudah kenyang,dibuat jadi baso aci versiku sendiri,beuhh mantap banget..\nYang mau order buruan ga usah ragu!!"
5,NaN,"2024-12-13 11:14 | Variasi: Isi 100 Uk. Mini,Cilok Jando / Gajih",bumbunya aku pake resep bumbu buat ayam goreng bawang putih friday eh cocok buat cilok
6,e*****y,"2022-10-21 18:58 | Variasi: Isi 100 Uk. Mini,Cilok Jando / Gajih","Kemasan rapi aman banget, Tekstur sesuai ekspektasi, rasa ok"
7,NaN,"2022-11-27 16:55 | Variasi: Isi 100 Uk. Mini,Cilok Jando / Gajih",Packing aman ..alhamdulillah paket dterima dlm kondisi baik. Tnx u seller
8,n*****a,"2024-10-27 09:44 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih","💢 Alhamdulillah paket telah diterima dgn baik sesuai orderan 🤲\n\nPengiriman cepat juga sampainya pdhl dari Tasikmalaya ke Jaksel hanya sehari , mantuull kereenn good job 🔥 \n\nPackaging luar biasa raaffiii ahmad dgn bubble wrap tebal + karton tebal pelapis + diberi nore "" urgent bahan mknan mudah basi harap segera dikirimkan "" 🔥\n\nHarga affordable murah & terjangkau 🔥\n\nBaso ciloknya bagus divacum , produk higienis & baik 👍\n\n\nHaturnuhun seller, shopee, pak kurir _ sukses & berkah selalu 🙏"
9,NaN,"2025-01-01 20:40 | Variasi: Isi 100 Uk. Mini,Cilok Jando / Gajih","Hujan2 ngemilnya cilok donk, bocil ku suka bgt, tekstur nya gak keras, next order lagi deh"

In [220]:
# Menambahkan kolom 'Kategori' dengan isi 'makanan' untuk semua baris
makanan['Kategori'] = 'Makanan'

makanan.head(10)

,Pengguna,Waktu,Ulasan,Kategori
0,t*****2,"2023-01-29 19:15 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih","Klo soal rasa cilok nya enak tektur'a lembut gurih gak kerasa pesen dapet yg isi'a gaji, klo dari segi packing sma pengiriman standar lah yah karna kan jauh di luar kota bogor",Makanan
1,NaN,"2024-09-12 22:38 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih","Datang sesuai pesanan, cilok gajih sapi ukuran sedang isi 50 butir. Rasanya enak, ada isian gajih didalam ciloknya. Aroma sedap dan gurih. \n\nCiloknya dikirim dengan kondisi di vacuum, jadi aman sampai ke tangan konsumen. Gak basi",Makanan
2,r*****0,"2024-11-04 22:40 | Variasi: Isi 100 Uk. Mini,Keju","Endul ciloknya udah sampai walau menunggu agak lama tapi pas sampai langsung dicobain mantul enak empuk kenyal nya pas gurih tinggal di kreasikan dengan bumbu kacang atau di buat cilok kuah seblak, next order lgi",Makanan
3,NaN,"2024-09-02 12:14 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih, Isi 50 Uk. Mini,Sinti","Belum dicoba soalnya baru dateng ,dari bentuk dan rupa sih oke \nAku pikir dapet bumbu kacang nya terpisah taunya cilok isi bumbu kacang 🤣 ,salah aku sih ngga teliti tapi mudah²an rasanya enak siapa tau bisa jadi langganan ,selernya ramah responnya cepet thanks seler 👌",Makanan
4,w*****u,"2024-11-11 08:05 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih","Ciloknya diterima dalam keadaan baik,divacum dan dipacking kardus.\nTekstur kenyalnya pas,ga alot,bentuknya juga besar2 yaaa..makan 5pcs sudah kenyang,dibuat jadi baso aci versiku sendiri,beuhh mantap banget..\nYang mau order buruan ga usah ragu!!",Makanan
5,NaN,"2024-12-13 11:14 | Variasi: Isi 100 Uk. Mini,Cilok Jando / Gajih",bumbunya aku pake resep bumbu buat ayam goreng bawang putih friday eh cocok buat cilok,Makanan
6,e*****y,"2022-10-21 18:58 | Variasi: Isi 100 Uk. Mini,Cilok Jando / Gajih","Kemasan rapi aman banget, Tekstur sesuai ekspektasi, rasa ok",Makanan
7,NaN,"2022-11-27 16:55 | Variasi: Isi 100 Uk. Mini,Cilok Jando / Gajih",Packing aman ..alhamdulillah paket dterima dlm kondisi baik. Tnx u seller,Makanan
8,n*****a,"2024-10-27 09:44 | Variasi: Isi 50 Uk. Sedang,Cilok Jando / Gajih","💢 Alhamdulillah paket telah diterima dgn baik sesuai orderan 🤲\n\nPengiriman cepat juga sampainya pdhl dari Tasikmalaya ke Jaksel hanya sehari , mantuull kereenn good job 🔥 \n\nPackaging luar biasa raaffiii ahmad dgn bubble wrap tebal + karton tebal pelapis + diberi nore "" urgent bahan mknan mudah basi harap segera dikirimkan "" 🔥\n\nHarga affordable murah & terjangkau 🔥\n\nBaso ciloknya bagus divacum , produk higienis & baik 👍\n\n\nHaturnuhun seller, shopee, pak kurir _ sukses & berkah selalu 🙏",Makanan
9,NaN,"2025-01-01 20:40 | Variasi: Isi 100 Uk. Mini,Cilok Jando / Gajih","Hujan2 ngemilnya cilok donk, bocil ku suka bgt, tekstur nya gak keras, next order lagi deh",Makanan

In [221]:
makanan_clean = makanan[["Kategori", "Ulasan"]]

makanan_clean.head(10)

,Kategori,Ulasan
0,Makanan,"Klo soal rasa cilok nya enak tektur'a lembut gurih gak kerasa pesen dapet yg isi'a gaji, klo dari segi packing sma pengiriman standar lah yah karna kan jauh di luar kota bogor"
1,Makanan,"Datang sesuai pesanan, cilok gajih sapi ukuran sedang isi 50 butir. Rasanya enak, ada isian gajih didalam ciloknya. Aroma sedap dan gurih. \n\nCiloknya dikirim dengan kondisi di vacuum, jadi aman sampai ke tangan konsumen. Gak basi"
2,Makanan,"Endul ciloknya udah sampai walau menunggu agak lama tapi pas sampai langsung dicobain mantul enak empuk kenyal nya pas gurih tinggal di kreasikan dengan bumbu kacang atau di buat cilok kuah seblak, next order lgi"
3,Makanan,"Belum dicoba soalnya baru dateng ,dari bentuk dan rupa sih oke \nAku pikir dapet bumbu kacang nya terpisah taunya cilok isi bumbu kacang 🤣 ,salah aku sih ngga teliti tapi mudah²an rasanya enak siapa tau bisa jadi langganan ,selernya ramah responnya cepet thanks seler 👌"
4,Makanan,"Ciloknya diterima dalam keadaan baik,divacum dan dipacking kardus.\nTekstur kenyalnya pas,ga alot,bentuknya juga besar2 yaaa..makan 5pcs sudah kenyang,dibuat jadi baso aci versiku sendiri,beuhh mantap banget..\nYang mau order buruan ga usah ragu!!"
5,Makanan,bumbunya aku pake resep bumbu buat ayam goreng bawang putih friday eh cocok buat cilok
6,Makanan,"Kemasan rapi aman banget, Tekstur sesuai ekspektasi, rasa ok"
7,Makanan,Packing aman ..alhamdulillah paket dterima dlm kondisi baik. Tnx u seller
8,Makanan,"💢 Alhamdulillah paket telah diterima dgn baik sesuai orderan 🤲\n\nPengiriman cepat juga sampainya pdhl dari Tasikmalaya ke Jaksel hanya sehari , mantuull kereenn good job 🔥 \n\nPackaging luar biasa raaffiii ahmad dgn bubble wrap tebal + karton tebal pelapis + diberi nore "" urgent bahan mknan mudah basi harap segera dikirimkan "" 🔥\n\nHarga affordable murah & terjangkau 🔥\n\nBaso ciloknya bagus divacum , produk higienis & baik 👍\n\n\nHaturnuhun seller, shopee, pak kurir _ sukses & berkah selalu 🙏"
9,Makanan,"Hujan2 ngemilnya cilok donk, bocil ku suka bgt, tekstur nya gak keras, next order lagi deh"

* Menggabungkan Seluruh Data Menjadi 1 Dataframe

In [222]:
# Gabungkan menjadi satu DataFrame
# ignore_index=True digunakan agar nomor urut (index) diulang dari 0 sampai akhir
Product_review_Shopee = pd.concat([elektronik_clean, makanan_clean, otomotif_clean, kecantikan_clean], ignore_index=True)

# Cek hasil penggabungan
print("Jumlah data per kategori:")
print(Product_review_Shopee['Kategori'].value_counts())
print(f"\nTotal data keseluruhan: {len(Product_review_Shopee)}")

Jumlah data per kategori:
Kategori
Otomotif      3636
Elektronik    3024
Makanan       3006
Kecantikan    3006
Name: count, dtype: int64

Total data keseluruhan: 12672

In [223]:
# Mengacak baris data agar model tidak belajar berdasarkan urutan
Product_review_Shopee = Product_review_Shopee.sample(frac=1).reset_index(drop=True)

* Menyimpan File Dataset Final

In [224]:
# Simpan hasil gabungan menjadi satu file master
Product_review_Shopee.to_csv('shopee_reviews_master.csv', index=False)

* Dataset Ulasan Produk Shopee

In [225]:
# Membaca dataset
shopee = pd.read_csv("E:/STT Terpadu Nurul Fikri/Semester 4/Natural Leanguage Processing/Project_Natural_Language_Processing/Data/shopee_reviews_master.csv")

# Menampilkan 10 Baris Pertama
shopee.head(10)

,Kategori,Ulasan
0,Otomotif,Agak berantakan di bagian dalam kurang rapi sedikit antara busa dan kain pelapis dan panas
1,Otomotif,"Sukses terus seller, Terima kasih pak 🙏💕kurir"
2,Makanan,Enak empuk\nPasti sy akan order lg
3,Kecantikan,"Gilaaa sih ini itungan jam udah sampe aja,thanks olay👍🏻👍🏻\nPacking super super rapi,discount nya juga lumayaan😊😊"
4,Elektronik,NaN
5,Elektronik,Sesuai pesanan. Mantap. Moga awet. Makasih semuanya. Belum dicoba
6,Elektronik,Lain kali cek dulu sebelum di kirim soalnya ada yang pecah
7,Makanan,⭐️⭐️⭐️⭐️⭐️⭐️
8,Otomotif,"Pengiriman cepat dan produk bagus, puas deh , juga recommended utk toko ini\nMakasih shopee"
9,Elektronik,"Pengiriman paket sesuai estimasi dan harapan saya. Packing bagus dan rapi, terimakasih buat seller yg telah mempacking produk kabel listrik pesanan saya..."

In [226]:
shopee.info

<bound method DataFrame.info of          Kategori  \
0        Otomotif
1        Otomotif
2         Makanan
3      Kecantikan
4      Elektronik
...           ...
12667  Kecantikan
12668    Otomotif
12669     Makanan
12670  Kecantikan
12671  Elektronik

                                                                                                                 Ulasan
0                            Agak berantakan di bagian dalam kurang rapi sedikit antara busa dan kain pelapis dan panas
1                                                                        Sukses terus seller, Terima kasih  pak 🙏💕kurir
2                                                                                    Enak empuk\nPasti sy akan order lg
3      Gilaaa sih ini itungan jam udah sampe aja,thanks olay👍🏻👍🏻\nPacking super super rapi,discount nya juga lumayaan😊😊
4                                                                                                                   NaN
...                                                                                                                 ...
12667                             mantaaaaaap abis olay ni cocok banget buat mamah aquuuuuwwwwwwwww mantap deh pokoknya
12668        Sangat KW, kaya helm yang 50k an 🫠 ditambah pengirimannya lama syekali ..\nSemoga ini jdi bahan evaluasi 🙏
12669                                                   Terima kasih barang sudah diterima dengan baik, mantap okkkk👍❤️
12670                                         Utk ke-3 kali..yg ini cepet response & pengirimannya. Packaging juga aman
12671                                                                                                               NaN

[12672 rows x 2 columns]>

* Cek Baris Kosong Setiap Kolom

In [227]:
# Cek jumlah total baris kosong di setiap kolom
print("Jumlah baris kosong per kolom:")
print(shopee.isnull().sum())

# Cek persentase baris kosong
print("\nPersentase baris kosong:")
print(shopee.isnull().mean() * 100)

Jumlah baris kosong per kolom:
Kategori       0
Ulasan      3015
dtype: int64

Persentase baris kosong:
Kategori     0.000000
Ulasan      23.792614
dtype: float64

* Hapus Baris Kosong Setiap Kolom

In [228]:
# Menghapus baris yang mengandung nilai kosong (NaN)
shopee.dropna(inplace=True)

# Reset index agar penomoran baris kembali rapi dari 0
shopee.reset_index(drop=True, inplace=True)

# Cek ulang untuk memastikan sudah 0
print("Jumlah baris kosong setelah dihapus:")
print(shopee.isnull().sum())
print(f"\nTotal data sekarang: {len(shopee)}")

Jumlah baris kosong setelah dihapus:
Kategori    0
Ulasan      0
dtype: int64

Total data sekarang: 9657

In [229]:
#copy data
data_shopee = shopee.copy()
data_shopee

,Kategori,Ulasan
0,Otomotif,Agak berantakan di bagian dalam kurang rapi sedikit antara busa dan kain pelapis dan panas
1,Otomotif,"Sukses terus seller, Terima kasih pak 🙏💕kurir"
2,Makanan,Enak empuk\nPasti sy akan order lg
3,Kecantikan,"Gilaaa sih ini itungan jam udah sampe aja,thanks olay👍🏻👍🏻\nPacking super super rapi,discount nya juga lumayaan😊😊"
4,Elektronik,Sesuai pesanan. Mantap. Moga awet. Makasih semuanya. Belum dicoba
...,...,...
9652,Makanan,Rasa nya lumayan enak gurih
9653,Kecantikan,mantaaaaaap abis olay ni cocok banget buat mamah aquuuuuwwwwwwwww mantap deh pokoknya
9654,Otomotif,"Sangat KW, kaya helm yang 50k an 🫠 ditambah pengirimannya lama syekali ..\nSemoga ini jdi bahan evaluasi 🙏"
9655,Makanan,"Terima kasih barang sudah diterima dengan baik, mantap okkkk👍❤️"
9656,Kecantikan,Utk ke-3 kali..yg ini cepet response & pengirimannya. Packaging juga aman

In [230]:
#set agar data bisa dilihat dengan lebar kolom maksimal
pd.set_option('display.max_colwidth', None)

*   Case Folding

In [231]:
def clean_ulasan(data_shopee, Ulasan):

    # Ubah data menjadi huruf kecil
    data_shopee['Ulasan_clean'] = data_shopee[Ulasan].str.lower()

    # Hapus spasi ganda atau baris kosong
    data_shopee['Ulasan_clean'] = data_shopee['Ulasan_clean'].str.strip()

    # Hapus tanda baca
    data_shopee['Ulasan_clean'] = data_shopee['Ulasan_clean'].str.replace('[^\w\s]', '', regex=True)

    # Hapus huruf yang berulang
    data_shopee['Ulasan_clean'] = data_shopee['Ulasan_clean'].str.replace(r'(.)\1{2,}', r'\1', regex=True)

    return data_shopee

<>:10: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:10: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4784\2312071238.py:10: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  data_shopee['Ulasan_clean'] = data_shopee['Ulasan_clean'].str.replace('[^\w\s]', '', regex=True)

In [232]:
# Jalankan fungsi
data_shopee_clean = clean_ulasan(data_shopee, 'Ulasan')

print(data_shopee_clean[['Ulasan', 'Ulasan_clean']])

                                                                                                                Ulasan  \
0                           Agak berantakan di bagian dalam kurang rapi sedikit antara busa dan kain pelapis dan panas
1                                                                       Sukses terus seller, Terima kasih  pak 🙏💕kurir
2                                                                                   Enak empuk\nPasti sy akan order lg
3     Gilaaa sih ini itungan jam udah sampe aja,thanks olay👍🏻👍🏻\nPacking super super rapi,discount nya juga lumayaan😊😊
4                                                    Sesuai pesanan. Mantap. Moga awet. Makasih semuanya. Belum dicoba
...                                                                                                                ...
9652                                                                                       Rasa nya lumayan enak gurih
9653                             mantaaaaaap abis olay ni cocok banget buat mamah aquuuuuwwwwwwwww mantap deh pokoknya
9654        Sangat KW, kaya helm yang 50k an 🫠 ditambah pengirimannya lama syekali ..\nSemoga ini jdi bahan evaluasi 🙏
9655                                                   Terima kasih barang sudah diterima dengan baik, mantap okkkk👍❤️
9656                                         Utk ke-3 kali..yg ini cepet response & pengirimannya. Packaging juga aman

                                                                                                Ulasan_clean
0                 agak berantakan di bagian dalam kurang rapi sedikit antara busa dan kain pelapis dan panas
1                                                                sukses terus seller terima kasih  pak kurir
2                                                                         enak empuk\npasti sy akan order lg
3     gila sih ini itungan jam udah sampe ajathanks olay\npacking super super rapidiscount nya juga lumayaan
4                                              sesuai pesanan mantap moga awet makasih semuanya belum dicoba
...                                                                                                      ...
9652                                                                             rasa nya lumayan enak gurih
9653                                    mantap abis olay ni cocok banget buat mamah aquw mantap deh pokoknya
9654   sangat kw kaya helm yang 50k an  ditambah pengirimannya lama syekali \nsemoga ini jdi bahan evaluasi
9655                                                terima kasih barang sudah diterima dengan baik mantap ok
9656                                    utk ke3 kaliyg ini cepet response  pengirimannya packaging juga aman

[9657 rows x 2 columns]

*   Stop Word Removal

In [233]:
#Load stop word
stopwords_url = "https://raw.githubusercontent.com/datascienceid/stopwords-bahasa-indonesia/master/stopwords_id_satya.txt"
stopwords = pd.read_csv(stopwords_url, header=None)[0].tolist()
stopwords

['ada',
 'adanya',
 'adalah',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'diantaranya',
 'antara',
 'antaranya',
 'diantara',
 'apa',
 'apaan',
 'mengapa',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'atau',
 'ataukah',
 'ataupun',
 'bagai',
 'bagaikan',
 'sebagai',
 'sebagainya',
 'bagaimana',
 'bagaimanapun',
 'sebagaimana',
 'bagaimanakah',
 'bagi',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'sebaliknya',
 'banyak',
 'sebanyak',
 'beberapa',
 'seberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'sebegini',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'sebegitu',
 'belum',
 'belumlah',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'betulkah',
 'sebetulnya',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'sebisanya',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'cuma',
 'percuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'sedemikian',
 'dengan',
 'depan',
 'di',
 'dia',
 'dialah',
 'dini',
 'diri',
 'dirinya',
 'terdiri',
 'dong',
 'dulu',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'terhadap',
 'terhadapnya',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'harus',
 'haruslah',
 'harusnya',
 'seharusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'sehingga',
 'ia',
 'ialah',
 'ibarat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jangan',
 'jangankan',
 'janganlah',
 'jika',
 'jikalau',
 'juga',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'dikarenakan',
 'karena',
 'karenanya',
 'ke',
 'kecil',
 'kemudian',
 'kenapa',
 'kepada',
 'kepadanya',
 'ketika',
 'seketika',
 'khususnya',
 'kini',
 'kinilah',
 'kiranya',
 'sekiranya',
 'kita',
 'kitalah',
 'kok',
 'lagi',
 'lagian',
 'selagi',
 'lah',
 'lain',
 'lainnya',
 'melainkan',
 'selaku',
 'lalu',
 'melalui',
 'terlalu',
 'lama',
 'lamanya',
 'selama',
 'selama',
 'selamanya',
 'lebih',
 'terlebih',
 'bermacam',
 'macam',
 'semacam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masih',
 'masihkah',
 'semasih',
 'masing',
 'mau',
 'maupun',
 'semaunya',
 'memang',
 'mereka',
 'merekalah',
 'meski',
 'meskipun',
 'semula',
 'mungkin',
 'mungkinkah',
 'nah',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'oleh',
 'olehnya',
 'seorang',
 'seseorang',
 'pada',
 'padanya',
 'padahal',
 'paling',
 'sepanjang',
 'pantas',
 'sepantasnya',
 'sepantasnyalah',
 'para',
 'pasti',
 'pastilah',
 'per',
 'pernah',
 'pula',
 'pun',
 'merupakan',
 'rupanya',
 'serupa',
 'saat',
 'saatnya',
 'sesaat',
 'saja',
 'sajalah',
 'saling',
 'bersama',
 'sama',
 'sesama',
 'sambil',
 'sampai',
 'sana',
 'sangat',
 'sangatlah',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebuah',
 'tersebut',
 'tersebutlah',
 'sedang',
 'sedangkan',
 'sedikit',
 'sedikitnya',
 'segala',
 'segalanya',
 'segera',
 'sesegera',
 'sejak',
 'sejenak',
 'sekali',
 'sekalian',
 'sekalipun',
 'sesekali',
 'sekaligus',
 'sekarang',
 'sekarang',
 'sekitar',
 'sekitarnya',
 'sela',
 'selain',
 'selalu',
 'seluruh',
 'seluruhnya',
 'semakin',
 'sementara',
 'sempat',
 'semua',
 'semuanya',
 'sendiri',
 'sendirinya',
 'seolah',
 'seperti',
 'sepertinya',
 'sering',
 'seringnya',
 'serta',
 'siapa',
 'siapakah',
 'siapapun',
 'disini',
 'disinilah',
 'sini',
 'sinilah',
 'sesuatu',
 'sesuatunya',
 'suatu',
 'sesudah',
 'sesudahnya',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tak',
 'tanpa',
 'setelah',
 'telah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tertentu',
 'seterusnya',
 'tapi',
 'tetapi',
 'setiap',
 'tiap',
 'setidaknya',
 'tidak',
 'tidakkah',
 'tidaklah',
 'toh',
 'waduh',
 'wah',
 'wahai',
 'sewaktu',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakni',
 'yang']

* Load Slang

In [234]:
#import library yang dibutuhkan
import re
import json
import requests

In [235]:
# crawl data slang
slang_url = "https://raw.githubusercontent.com/louisowen6/NLP_bahasa_resources/master/combined_slang_words.txt"
response = requests.get(slang_url)
slang_dict = json.loads(response.text)
print(slang_dict)

{'@': 'di', 'abis': 'habis', 'ad': 'ada', 'adlh': 'adalah', 'afaik': 'as far as i know', 'ahaha': 'haha', 'aj': 'saja', 'ajep-ajep': 'dunia gemerlap', 'ak': 'saya', 'akika': 'aku', 'akkoh': 'aku', 'akuwh': 'aku', 'alay': 'norak', 'alow': 'halo', 'ambilin': 'ambilkan', 'ancur': 'hancur', 'anjrit': 'anjing', 'anter': 'antar', 'ap2': 'apa-apa', 'apasih': 'apa sih', 'apes': 'sial', 'aps': 'apa', 'aq': 'saya', 'aquwh': 'aku', 'asbun': 'asal bunyi', 'aseekk': 'asyik', 'asekk': 'asyik', 'asem': 'asam', 'aspal': 'asli tetapi palsu', 'astul': 'asal tulis', 'ato': 'atau', 'au ah': 'tidak mau tahu', 'awak': 'saya', 'ay': 'sayang', 'ayank': 'sayang', 'b4': 'sebelum', 'bakalan': 'akan', 'bandes': 'bantuan desa', 'bangedh': 'banget', 'banpol': 'bantuan polisi', 'banpur': 'bantuan tempur', 'basbang': 'basi', 'bcanda': 'bercanda', 'bdg': 'bandung', 'begajulan': 'nakal', 'beliin': 'belikan', 'bencong': 'banci', 'bentar': 'sebentar', 'ber3': 'bertiga', 'beresin': 'membereskan', 'bete': 'bosan', 'beud': 'banget', 'bg': 'abang', 'bgmn': 'bagaimana', 'bgt': 'banget', 'bijimane': 'bagaimana', 'bintal': 'bimbingan mental', 'bkl': 'akan', 'bknnya': 'bukannya', 'blegug': 'bodoh', 'blh': 'boleh', 'bln': 'bulan', 'blum': 'belum', 'bnci': 'benci', 'bnran': 'yang benar', 'bodor': 'lucu', 'bokap': 'ayah', 'boker': 'buang air besar', 'bokis': 'bohong', 'boljug': 'boleh juga', 'bonek': 'bocah nekat', 'boyeh': 'boleh', 'br': 'baru', 'brg': 'bareng', 'bro': 'saudara laki-laki', 'bru': 'baru', 'bs': 'bisa', 'bsen': 'bosan', 'bt': 'buat', 'btw': 'ngomong-ngomong', 'buaya': 'tidak setia', 'bubbu': 'tidur', 'bubu': 'tidur', 'bumil': 'ibu hamil', 'bw': 'bawa', 'bwt': 'buat', 'byk': 'banyak', 'byrin': 'bayarkan', 'cabal': 'sabar', 'cadas': 'keren', 'calo': 'makelar', 'can': 'belum', 'capcus': 'pergi', 'caper': 'cari perhatian', 'ce': 'cewek', 'cekal': 'cegah tangkal', 'cemen': 'penakut', 'cengengesan': 'tertawa', 'cepet': 'cepat', 'cew': 'cewek', 'chuyunk': 'sayang', 'cimeng': 'ganja', 'cipika cipiki': 'cium pipi kanan cium pipi kiri', 'ciyh': 'sih', 'ckepp': 'cakep', 'ckp': 'cakep', 'cmiiw': "correct me if i'm wrong", 'cmpur': 'campur', 'cong': 'banci', 'conlok': 'cinta lokasi', 'cowwyy': 'maaf', 'cp': 'siapa', 'cpe': 'capek', 'cppe': 'capek', 'cucok': 'cocok', 'cuex': 'cuek', 'cumi': 'Cuma miscall', 'cups': 'culun', 'curanmor': 'pencurian kendaraan bermotor', 'curcol': 'curahan hati colongan', 'cwek': 'cewek', 'cyin': 'cinta', 'd': 'di', 'dah': 'deh', 'dapet': 'dapat', 'de': 'adik', 'dek': 'adik', 'demen': 'suka', 'deyh': 'deh', 'dgn': 'dengan', 'diancurin': 'dihancurkan', 'dimaafin': 'dimaafkan', 'dimintak': 'diminta', 'disono': 'di sana', 'dket': 'dekat', 'dkk': 'dan kawan-kawan', 'dll': 'dan lain-lain', 'dlu': 'dulu', 'dngn': 'dengan', 'dodol': 'bodoh', 'doku': 'uang', 'dongs': 'dong', 'dpt': 'dapat', 'dri': 'dari', 'drmn': 'darimana', 'drtd': 'dari tadi', 'dst': 'dan seterusnya', 'dtg': 'datang', 'duh': 'aduh', 'duren': 'durian', 'ed': 'edisi', 'egp': 'emang gue pikirin', 'eke': 'aku', 'elu': 'kamu', 'emangnya': 'memangnya', 'emng': 'memang', 'endak': 'tidak', 'enggak': 'tidak', 'envy': 'iri', 'ex': 'mantan', 'fax': 'facsimile', 'fifo': 'first in first out', 'folbek': 'follow back', 'fyi': 'sebagai informasi', 'gaada': 'tidak ada uang', 'gag': 'tidak', 'gaje': 'tidak jelas', 'gak papa': 'tidak apa-apa', 'gan': 'juragan', 'gaptek': 'gagap teknologi', 'gatek': 'gagap teknologi', 'gawe': 'kerja', 'gbs': 'tidak bisa', 'gebetan': 'orang yang disuka', 'geje': 'tidak jelas', 'gepeng': 'gelandangan dan pengemis', 'ghiy': 'lagi', 'gile': 'gila', 'gimana': 'bagaimana', 'gino': 'gigi nongol', 'githu': 'gitu', 'gj': 'tidak jelas', 'gmana': 'bagaimana', 'gn': 'begini', 'goblok': 'bodoh', 'golput': 'golongan putih', 'gowes': 'mengayuh sepeda', 'gpny': 'tidak punya', 'gr': 'gede rasa', 'gretongan': 'gratisan', 'gtau': 'tidak tahu', 'gua': 'saya', 'guoblok': 'goblok', 'gw': 'saya', 'ha': 'tertawa', 'haha': 'tertawa', 'hallow': 'halo', 'hankam': 'pertahanan dan keamanan', 'hehe': 'he', 'helo': 'halo', 'hey': 'hai', 'hlm': 'halaman', 'hny': 'hanya', 'hoax': 'isu bohong', 'hr': 'hari', 'hrus': 'harus', 'hubdar': 'perhubungan darat', 'huff': 'mengeluh', 'hum': 'rumah', 'humz': 'rumah', 'ilang': 'hilang', 'ilfil': 'tidak suka', 'imho': 'in my humble opinion', 'imoetz': 'imut', 'item': 'hitam', 'itungan': 'hitungan', 'iye': 'iya', 'ja': 'saja', 'jadiin': 'jadi', 'jaim': 'jaga image', 'jayus': 'tidak lucu', 'jdi': 'jadi', 'jem': 'jam', 'jga': 'juga', 'jgnkan': 'jangankan', 'jir': 'anjing', 'jln': 'jalan', 'jomblo': 'tidak punya pacar', 'jubir': 'juru bicara', 'jutek': 'galak', 'k': 'ke', 'kab': 'kabupaten', 'kabor': 'kabur', 'kacrut': 'kacau', 'kadiv': 'kepala divisi', 'kagak': 'tidak', 'kalo': 'kalau', 'kampret': 'sialan', 'kamtibmas': 'keamanan dan ketertiban masyarakat', 'kamuwh': 'kamu', 'kanwil': 'kantor wilayah', 'karna': 'karena', 'kasubbag': 'kepala subbagian', 'katrok': 'kampungan', 'kayanya': 'kayaknya', 'kbr': 'kabar', 'kdu': 'harus', 'kec': 'kecamatan', 'kejurnas': 'kejuaraan nasional', 'kekeuh': 'keras kepala', 'kel': 'kelurahan', 'kemaren': 'kemarin', 'kepengen': 'mau', 'kepingin': 'mau', 'kepsek': 'kepala sekolah', 'kesbang': 'kesatuan bangsa', 'kesra': 'kesejahteraan rakyat', 'ketrima': 'diterima', 'kgiatan': 'kegiatan', 'kibul': 'bohong', 'kimpoi': 'kawin', 'kl': 'kalau', 'klianz': 'kalian', 'kloter': 'kelompok terbang', 'klw': 'kalau', 'km': 'kamu', 'kmps': 'kampus', 'kmrn': 'kemarin', 'knal': 'kenal', 'knp': 'kenapa', 'kodya': 'kota madya', 'komdis': 'komisi disiplin', 'komsov': 'komunis sovyet', 'kongkow': 'kumpul bareng teman-teman', 'kopdar': 'kopi darat', 'korup': 'korupsi', 'kpn': 'kapan', 'krenz': 'keren', 'krm': 'kirim', 'kt': 'kita', 'ktmu': 'ketemu', 'ktr': 'kantor', 'kuper': 'kurang pergaulan', 'kw': 'imitasi', 'kyk': 'seperti', 'la': 'lah', 'lam': 'salam', 'lamp': 'lampiran', 'lanud': 'landasan udara', 'latgab': 'latihan gabungan', 'lebay': 'berlebihan', 'leh': 'boleh', 'lelet': 'lambat', 'lemot': 'lambat', 'lgi': 'lagi', 'lgsg': 'langsung', 'liat': 'lihat', 'litbang': 'penelitian dan pengembangan', 'lmyn': 'lumayan', 'lo': 'kamu', 'loe': 'kamu', 'lola': 'lambat berfikir', 'louph': 'cinta', 'low': 'kalau', 'lp': 'lupa', 'luber': 'langsung, umum, bebas, dan rahasia', 'luchuw': 'lucu', 'lum': 'belum', 'luthu': 'lucu', 'lwn': 'lawan', 'maacih': 'terima kasih', 'mabal': 'bolos', 'macem': 'macam', 'macih': 'masih', 'maem': 'makan', 'magabut': 'makan gaji buta', 'maho': 'homo', 'mak jang': 'kaget', 'maksain': 'memaksa', 'malem': 'malam', 'mam': 'makan', 'maneh': 'kamu', 'maniez': 'manis', 'mao': 'mau', 'masukin': 'masukkan', 'melu': 'ikut', 'mepet': 'dekat sekali', 'mgu': 'minggu', 'migas': 'minyak dan gas bumi', 'mikol': 'minuman beralkohol', 'miras': 'minuman keras', 'mlah': 'malah', 'mngkn': 'mungkin', 'mo': 'mau', 'mokad': 'mati', 'moso': 'masa', 'mpe': 'sampai', 'msk': 'masuk', 'mslh': 'masalah', 'mt': 'makan teman', 'mubes': 'musyawarah besar', 'mulu': 'melulu', 'mumpung': 'selagi', 'munas': 'musyawarah nasional', 'muntaber': 'muntah dan berak', 'musti': 'mesti', 'muupz': 'maaf', 'mw': 'now watching', 'n': 'dan', 'nanam': 'menanam', 'nanya': 'bertanya', 'napa': 'kenapa', 'napi': 'narapidana', 'napza': 'narkotika, alkohol, psikotropika, dan zat adiktif ', 'narkoba': 'narkotika, psikotropika, dan obat terlarang', 'nasgor': 'nasi goreng', 'nda': 'tidak', 'ndiri': 'sendiri', 'ne': 'ini', 'nekolin': 'neokolonialisme', 'nembak': 'menyatakan cinta', 'ngabuburit': 'menunggu berbuka puasa', 'ngaku': 'mengaku', 'ngambil': 'mengambil', 'nganggur': 'tidak punya pekerjaan', 'ngapah': 'kenapa', 'ngaret': 'terlambat', 'ngasih': 'memberikan', 'ngebandel': 'berbuat bandel', 'ngegosip': 'bergosip', 'ngeklaim': 'mengklaim', 'ngeksis': 'menjadi eksis', 'ngeles': 'berkilah', 'ngelidur': 'menggigau', 'ngerampok': 'merampok', 'ngga': 'tidak', 'ngibul': 'berbohong', 'ngiler': 'mau', 'ngiri': 'iri', 'ngisiin': 'mengisikan', 'ngmng': 'bicara', 'ngomong': 'bicara', 'ngubek2': 'mencari-cari', 'ngurus': 'mengurus', 'nie': 'ini', 'nih': 'ini', 'niyh': 'nih', 'nmr': 'nomor', 'nntn': 'nonton', 'nobar': 'nonton bareng', 'np': 'now playing', 'ntar': 'nanti', 'ntn': 'nonton', 'numpuk': 'bertumpuk', 'nutupin': 'menutupi', 'nyari': 'mencari', 'nyekar': 'menyekar', 'nyicil': 'mencicil', 'nyoblos': 'mencoblos', 'nyokap': 'ibu', 'ogah': 'tidak mau', 'ol': 'online', 'ongkir': 'ongkos kirim', 'oot': 'out of topic', 'org2': 'orang-orang', 'ortu': 'orang tua', 'otda': 'otonomi daerah', 'otw': 'on the way, sedang di jalan', 'pacal': 'pacar', 'pake': 'pakai', 'pala': 'kepala', 'pansus': 'panitia khusus', 'parpol': 'partai politik', 'pasutri': 'pasangan suami istri', 'pd': 'pada', 'pede': 'percaya diri', 'pelatnas': 'pemusatan latihan nasional', 'pemda': 'pemerintah daerah', 'pemkot': 'pemerintah kota', 'pemred': 'pemimpin redaksi', 'penjas': 'pendidikan jasmani', 'perda': 'peraturan daerah', 'perhatiin': 'perhatikan', 'pesenan': 'pesanan', 'pgang': 'pegang', 'pi': 'tapi', 'pilkada': 'pemilihan kepala daerah', 'pisan': 'sangat', 'pk': 'penjahat kelamin', 'plg': 'paling', 'pmrnth': 'pemerintah', 'polantas': 'polisi lalu lintas', 'ponpes': 'pondok pesantren', 'pp': 'pulang pergi', 'prg': 'pergi', 'prnh': 'pernah', 'psen': 'pesan', 'pst': 'pasti', 'pswt': 'pesawat', 'pw': 'posisi nyaman', 'qmu': 'kamu', 'rakor': 'rapat koordinasi', 'ranmor': 'kendaraan bermotor', 're': 'reply', 'ref': 'referensi', 'rehab': 'rehabilitasi', 'rempong': 'sulit', 'repp': 'balas', 'restik': 'reserse narkotika', 'rhs': 'rahasia', 'rmh': 'rumah', 'ru': 'baru', 'ruko': 'rumah toko', 'rusunawa': 'rumah susun sewa', 'ruz': 'terus', 'saia': 'saya', 'salting': 'salah tingkah', 'sampe': 'sampai', 'samsek': 'sama sekali', 'sapose': 'siapa', 'satpam': 'satuan pengamanan', 'sbb': 'sebagai berikut', 'sbh': 'sebuah', 'sbnrny': 'sebenarnya', 'scr': 'secara', 'sdgkn': 'sedangkan', 'sdkt': 'sedikit', 'se7': 'setuju', 'sebelas dua belas': 'mirip', 'sembako': 'sembilan bahan pokok', 'sempet': 'sempat', 'sendratari': 'seni drama tari', 'sgt': 'sangat', 'shg': 'sehingga', 'siech': 'sih', 'sikon': 'situasi dan kondisi', 'sinetron': 'sinema elektronik', 'siramin': 'siramkan', 'sj': 'saja', 'skalian': 'sekalian', 'sklh': 'sekolah', 'skt': 'sakit', 'slesai': 'selesai', 'sll': 'selalu', 'slma': 'selama', 'slsai': 'selesai', 'smpt': 'sempat', 'smw': 'semua', 'sndiri': 'sendiri', 'soljum': 'sholat jumat', 'songong': 'sombong', 'sory': 'maaf', 'sosek': 'sosial-ekonomi', 'sotoy': 'sok tahu', 'spa': 'siapa', 'sppa': 'siapa', 'spt': 'seperti', 'srtfkt': 'sertifikat', 'stiap': 'setiap', 'stlh': 'setelah', 'suk': 'masuk', 'sumpek': 'sempit', 'syg': 'sayang', 't4': 'tempat', 'tajir': 'kaya', 'tau': 'tahu', 'taw': 'tahu', 'td': 'tadi', 'tdk': 'tidak', 'teh': 'kakak perempuan', 'telat': 'terlambat', 'telmi': 'telat berpikir', 'temen': 'teman', 'tengil': 'menyebalkan', 'tepar': 'terkapar', 'tggu': 'tunggu', 'tgu': 'tunggu', 'thankz': 'terima kasih', 'thn': 'tahun', 'tilang': 'bukti pelanggaran', 'tipiwan': 'TvOne', 'tks': 'terima kasih', 'tlp': 'telepon', 'tls': 'tulis', 'tmbah': 'tambah', 'tmen2': 'teman-teman', 'tmpah': 'tumpah', 'tmpt': 'tempat', 'tngu': 'tunggu', 'tnyta': 'ternyata', 'tokai': 'tai', 'toserba': 'toko serba ada', 'tpi': 'tapi', 'trdhulu': 'terdahulu', 'trima': 'terima kasih', 'trm': 'terima', 'trs': 'terus', 'trutama': 'terutama', 'ts': 'penulis', 'tst': 'tahu sama tahu', 'ttg': 'tentang', 'tuch': 'tuh', 'tuir': 'tua', 'tw': 'tahu', 'u': 'kamu', 'ud': 'sudah', 'udah': 'sudah', 'ujg': 'ujung', 'ul': 'ulangan', 'unyu': 'lucu', 'uplot': 'unggah', 'urang': 'saya', 'usah': 'perlu', 'utk': 'untuk', 'valas': 'valuta asing', 'w/': 'dengan', 'wadir': 'wakil direktur', 'wamil': 'wajib militer', 'warkop': 'warung kopi', 'warteg': 'warung tegal', 'wat': 'buat', 'wkt': 'waktu', 'wtf': 'what the fuck', 'xixixi': 'tertawa', 'ya': 'iya', 'yap': 'iya', 'yaudah': 'ya sudah', 'yawdah': 'ya sudah', 'yg': 'yang', 'yl': 'yang lain', 'yo': 'iya', 'yowes': 'ya sudah', 'yup': 'iya', '7an': 'tujuan', 'ababil': 'abg labil', 'acc': 'accord', 'adlah': 'adalah', 'adoh': 'aduh', 'aha': 'tertawa', 'aing': 'saya', 'aja': 'saja', 'ajj': 'saja', 'aka': 'dikenal juga sebagai', 'akko': 'aku', 'akku': 'aku', 'akyu': 'aku', 'aljasa': 'asal jadi saja', 'ama': 'sama', 'ambl': 'ambil', 'anjir': 'anjing', 'ank': 'anak', 'ap': 'apa', 'apaan': 'apa', 'ape': 'apa', 'aplot': 'unggah', 'apva': 'apa', 'aqu': 'aku', 'asap': 'sesegera mungkin', 'aseek': 'asyik', 'asek': 'asyik', 'aseknya': 'asyiknya', 'asoy': 'asyik', 'astrojim': 'astagfirullahaladzim', 'ath': 'kalau begitu', 'atuh': 'kalau begitu', 'ava': 'avatar', 'aws': 'awas', 'ayang': 'sayang', 'ayok': 'ayo', 'bacot': 'banyak bicara', 'bales': 'balas', 'bangdes': 'pembangunan desa', 'bangkotan': 'tua', 'banpres': 'bantuan presiden', 'bansarkas': 'bantuan sarana kesehatan', 'bazis': 'badan amal, zakat, infak, dan sedekah', 'bcoz': 'karena', 'beb': 'sayang', 'bejibun': 'banyak', 'belom': 'belum', 'bener': 'benar', 'ber2': 'berdua', 'berdikari': 'berdiri di atas kaki sendiri', 'bet': 'banget', 'beti': 'beda tipis', 'beut': 'banget', 'bgd': 'banget', 'bgs': 'bagus', 'bhubu': 'tidur', 'bimbuluh': 'bimbingan dan penyuluhan', 'bisi': 'kalau-kalau', 'bkn': 'bukan', 'bl': 'beli', 'blg': 'bilang', 'blm': 'belum', 'bls': 'balas', 'bnchi': 'benci', 'bngung': 'bingung', 'bnyk': 'banyak', 'bohay': 'badan aduhai', 'bokep': 'porno', 'bokin': 'pacar', 'bole': 'boleh', 'bolot': 'bodoh', 'bonyok': 'ayah ibu', 'bpk': 'bapak', 'brb': 'segera kembali', 'brngkt': 'berangkat', 'brp': 'berapa', 'brur': 'saudara laki-laki', 'bsa': 'bisa', 'bsk': 'besok', 'bu_bu': 'tidur', 'bubarin': 'bubarkan', 'buber': 'buka bersama', 'bujubune': 'luar biasa', 'buser': 'buru sergap', 'bwhn': 'bawahan', 'byar': 'bayar', 'byr': 'bayar', 'c8': 'chat', 'cabut': 'pergi', 'caem': 'cakep', 'cama-cama': 'sama-sama', 'cangcut': 'celana dalam', 'cape': 'capek', 'caur': 'jelek', 'cekak': 'tidak ada uang', 'cekidot': 'coba lihat', 'cemplungin': 'cemplungkan', 'ceper': 'pendek', 'ceu': 'kakak perempuan', 'cewe': 'cewek', 'cibuk': 'sibuk', 'cin': 'cinta', 'ciye': 'cie', 'ckck': 'ck', 'clbk': 'cinta lama bersemi kembali', 'cmpr': 'campur', 'cnenk': 'senang', 'congor': 'mulut', 'cow': 'cowok', 'coz': 'karena', 'cpa': 'siapa', 'gokil': 'gila', 'gombal': 'suka merayu', 'gpl': 'tidak pakai lama', 'gpp': 'tidak apa-apa', 'gretong': 'gratis', 'gt': 'begitu', 'gtw': 'tidak tahu', 'gue': 'saya', 'guys': 'teman-teman', 'gws': 'cepat sembuh', 'haghaghag': 'tertawa', 'hakhak': 'tertawa', 'handak': 'bahan peledak', 'hansip': 'pertahanan sipil', 'hellow': 'halo', 'helow': 'halo', 'hi': 'hai', 'hlng': 'hilang', 'hnya': 'hanya', 'houm': 'rumah', 'hrs': 'harus', 'hubad': 'hubungan angkatan darat', 'hubla': 'perhubungan laut', 'huft': 'mengeluh', 'humas': 'hubungan masyarakat', 'idk': 'saya tidak tahu', 'ilfeel': 'tidak suka', 'imba': 'jago sekali', 'imoet': 'imut', 'info': 'informasi', 'itung': 'hitung', 'isengin': 'bercanda', 'iyala': 'iya lah', 'iyo': 'iya', 'jablay': 'jarang dibelai', 'jadul': 'jaman dulu', 'jancuk': 'anjing', 'jd': 'jadi', 'jdikan': 'jadikan', 'jg': 'juga', 'jgn': 'jangan', 'jijay': 'jijik', 'jkt': 'jakarta', 'jnj': 'janji', 'jth': 'jatuh', 'jurdil': 'jujur adil', 'jwb': 'jawab', 'ka': 'kakak', 'kabag': 'kepala bagian', 'kacian': 'kasihan', 'kadit': 'kepala direktorat', 'kaga': 'tidak', 'kaka': 'kakak', 'kamtib': 'keamanan dan ketertiban', 'kamuh': 'kamu', 'kamyu': 'kamu', 'kapt': 'kapten', 'kasat': 'kepala satuan', 'kasubbid': 'kepala subbidang', 'kau': 'kamu', 'kbar': 'kabar', 'kcian': 'kasihan', 'keburu': 'terlanjur', 'kedubes': 'kedutaan besar', 'kek': 'seperti', 'keknya': 'kayaknya', 'keliatan': 'kelihatan', 'keneh': 'masih', 'kepikiran': 'terpikirkan', 'kepo': 'mau tahu urusan orang', 'kere': 'tidak punya uang', 'kesian': 'kasihan', 'ketauan': 'ketahuan', 'keukeuh': 'keras kepala', 'khan': 'kan', 'kibus': 'kaki busuk', 'kk': 'kakak', 'klian': 'kalian', 'klo': 'kalau', 'kluarga': 'keluarga', 'klwrga': 'keluarga', 'kmari': 'kemari', 'kmpus': 'kampus', 'kn': 'kan', 'knl': 'kenal', 'knpa': 'kenapa', 'kog': 'kok', 'kompi': 'komputer', 'komtiong': 'komunis Tiongkok', 'konjen': 'konsulat jenderal', 'koq': 'kok', 'kpd': 'kepada', 'kptsan': 'keputusan', 'krik': 'garing', 'krn': 'karena', 'ktauan': 'ketahuan', 'ktny': 'katanya', 'kudu': 'harus', 'kuq': 'kok', 'ky': 'seperti', 'kykny': 'kayanya', 'laka': 'kecelakaan', 'lambreta': 'lambat', 'lansia': 'lanjut usia', 'lapas': 'lembaga pemasyarakatan', 'lbur': 'libur', 'lekong': 'laki-laki', 'lg': 'lagi', 'lgkp': 'lengkap', 'lht': 'lihat', 'linmas': 'perlindungan masyarakat', 'lmyan': 'lumayan', 'lngkp': 'lengkap', 'loch': 'loh', 'lol': 'tertawa', 'lom': 'belum', 'loupz': 'cinta', 'lowh': 'kamu', 'lu': 'kamu', 'luchu': 'lucu', 'luff': 'cinta', 'luph': 'cinta', 'lw': 'kamu', 'lwt': 'lewat', 'maaciw': 'terima kasih', 'mabes': 'markas besar', 'macem-macem': 'macam-macam', 'madesu': 'masa depan suram', 'maen': 'main', 'mahatma': 'maju sehat bersama', 'mak': 'ibu', 'makasih': 'terima kasih', 'malah': 'bahkan', 'malu2in': 'memalukan', 'mamz': 'makan', 'manies': 'manis', 'mantep': 'mantap', 'markus': 'makelar kasus', 'mba': 'mbak', 'mending': 'lebih baik', 'mgkn': 'mungkin', 'mhn': 'mohon', 'miker': 'minuman keras', 'milis': 'mailing list', 'mksd': 'maksud', 'mls': 'malas', 'mnt': 'minta', 'moge': 'motor gede', 'mokat': 'mati', 'mosok': 'masa', 'msh': 'masih', 'mskpn': 'meskipun', 'msng2': 'masing-masing', 'muahal': 'mahal', 'muker': 'musyawarah kerja', 'mumet': 'pusing', 'muna': 'munafik', 'munaslub': 'musyawarah nasional luar biasa', 'musda': 'musyawarah daerah', 'muup': 'maaf', 'muuv': 'maaf', 'nal': 'kenal', 'nangis': 'menangis', 'naon': 'apa', 'napol': 'narapidana politik', 'naq': 'anak', 'narsis': 'bangga pada diri sendiri', 'nax': 'anak', 'ndak': 'tidak', 'ndut': 'gendut', 'nekolim': 'neokolonialisme', 'nelfon': 'menelepon', 'ngabis2in': 'menghabiskan', 'ngakak': 'tertawa', 'ngambek': 'marah', 'ngampus': 'pergi ke kampus', 'ngantri': 'mengantri', 'ngapain': 'sedang apa', 'ngaruh': 'berpengaruh', 'ngawur': 'berbicara sembarangan', 'ngeceng': 'kumpul bareng-bareng', 'ngeh': 'sadar', 'ngekos': 'tinggal di kos', 'ngelamar': 'melamar', 'ngeliat': 'melihat', 'ngemeng': 'bicara terus-terusan', 'ngerti': 'mengerti', 'nggak': 'tidak', 'ngikut': 'ikut', 'nginep': 'menginap', 'ngisi': 'mengisi', 'ngmg': 'bicara', 'ngocol': 'lucu', 'ngomongin': 'membicarakan', 'ngumpul': 'berkumpul', 'ni': 'ini', 'nyasar': 'tersesat', 'nyariin': 'mencari', 'nyiapin': 'mempersiapkan', 'nyiram': 'menyiram', 'nyok': 'ayo', 'o/': 'oleh', 'ok': 'ok', 'priksa': 'periksa', 'pro': 'profesional', 'psn': 'pesan', 'psti': 'pasti', 'puanas': 'panas', 'qmo': 'kamu', 'qt': 'kita', 'rame': 'ramai', 'raskin': 'rakyat miskin', 'red': 'redaksi', 'reg': 'register', 'rejeki': 'rezeki', 'renstra': 'rencana strategis', 'reskrim': 'reserse kriminal', 'sni': 'sini', 'somse': 'sombong sekali', 'sorry': 'maaf', 'sosbud': 'sosial-budaya', 'sospol': 'sosial-politik', 'sowry': 'maaf', 'spd': 'sepeda', 'sprti': 'seperti', 'spy': 'supaya', 'stelah': 'setelah', 'subbag': 'subbagian', 'sumbangin': 'sumbangkan', 'sy': 'saya', 'syp': 'siapa', 'tabanas': 'tabungan pembangunan nasional', 'tar': 'nanti', 'taun': 'tahun', 'tawh': 'tahu', 'tdi': 'tadi', 'te2p': 'tetap', 'tekor': 'rugi', 'telkom': 'telekomunikasi', 'telp': 'telepon', 'temen2': 'teman-teman', 'tengok': 'menjenguk', 'terbitin': 'terbitkan', 'tgl': 'tanggal', 'thanks': 'terima kasih', 'thd': 'terhadap', 'thx': 'terima kasih', 'tipi': 'TV', 'tkg': 'tukang', 'tll': 'terlalu', 'tlpn': 'telepon', 'tman': 'teman', 'tmbh': 'tambah', 'tmn2': 'teman-teman', 'tmph': 'tumpah', 'tnda': 'tanda', 'tnh': 'tanah', 'togel': 'toto gelap', 'tp': 'tapi', 'tq': 'terima kasih', 'trgntg': 'tergantung', 'trims': 'terima kasih', 'cb': 'coba', 'y': 'ya', 'munfik': 'munafik', 'reklamuk': 'reklamasi', 'sma': 'sama', 'tren': 'trend', 'ngehe': 'kesal', 'mz': 'mas', 'analisise': 'analisis', 'sadaar': 'sadar', 'sept': 'september', 'nmenarik': 'menarik', 'zonk': 'bodoh'

*   Stemming

In [236]:
#install sastrawi untuk bahasa indonesia
!pip install Sastrawi

Requirement already satisfied: Sastrawi in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.0.1)

In [237]:
#import library sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [238]:
#using sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [239]:
# Cleaning Text dengan regex Library
def clean_text(text):

    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'(.)\1{2,}', r'\1', text)
    words = text.split()

    # normalisasi slang
    words = [slang_dict[word] if word in slang_dict else word for word in words]


    text = " ".join(words)

    # stemming
    text = stemmer.stem(text)

    return text

In [240]:
# Jalankan Pipeline
data_shopee_clean['clean_ulasan'] = data_shopee_clean['Ulasan'].apply(clean_text)

print(data_shopee_clean[['Ulasan', 'clean_ulasan']])

                                                                                                                Ulasan  \
0                           Agak berantakan di bagian dalam kurang rapi sedikit antara busa dan kain pelapis dan panas
1                                                                       Sukses terus seller, Terima kasih  pak 🙏💕kurir
2                                                                                   Enak empuk\nPasti sy akan order lg
3     Gilaaa sih ini itungan jam udah sampe aja,thanks olay👍🏻👍🏻\nPacking super super rapi,discount nya juga lumayaan😊😊
4                                                    Sesuai pesanan. Mantap. Moga awet. Makasih semuanya. Belum dicoba
...                                                                                                                ...
9652                                                                                       Rasa nya lumayan enak gurih
9653                             mantaaaaaap abis olay ni cocok banget buat mamah aquuuuuwwwwwwwww mantap deh pokoknya
9654        Sangat KW, kaya helm yang 50k an 🫠 ditambah pengirimannya lama syekali ..\nSemoga ini jdi bahan evaluasi 🙏
9655                                                   Terima kasih barang sudah diterima dengan baik, mantap okkkk👍❤️
9656                                         Utk ke-3 kali..yg ini cepet response & pengirimannya. Packaging juga aman

                                                                                                clean_ulasan
0                          agak beranta di bagi dalam kurang rapi sedikit antara busa dan kain lap dan panas
1                                                                 sukses terus seller terima kasih pak kurir
2                                                                      enak empuk pasti saya akan order lagi
3     gila sih ini hitung jam sudah sampai ajathanks olay packing super super rapidiscount nya juga lumayaan
4                                                sesuai pesan mantap moga awet terima kasih semua belum coba
...                                                                                                      ...
9652                                                                             rasa nya lumayan enak gurih
9653                                     mantap habis olay ini cocok banget buat mamah aquw mantap deh pokok
9654             sangat imitasi kaya helm yang 50k an tambah kirim lama syekali moga ini jadi bahan evaluasi
9655                                                  terima kasih barang sudah terima dengan baik mantap ok
9656                                           untuk ke3 kaliyg ini cepat response kirim packaging juga aman

[9657 rows x 2 columns]

* Tokenize

In [241]:
!pip install spacy
import spacy

nlp = spacy.blank("id")  # tokenizer saja

def spacy_tokenize(text):
    doc = nlp(text)
    return [token.text for token in doc]

data_shopee_clean['tokens'] = data_shopee_clean['clean_ulasan'].apply(spacy_tokenize)

Requirement already satisfied: spacy in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.8.13)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (2.4.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (2.33.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (2.13.3)
Requirement already satisfied: jinja2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (82.0.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.3)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.2.1 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->spacy) (3.0.3)

In [242]:
data_shopee_clean

,Kategori,Ulasan,Ulasan_clean,clean_ulasan,tokens
0,Otomotif,Agak berantakan di bagian dalam kurang rapi sedikit antara busa dan kain pelapis dan panas,agak berantakan di bagian dalam kurang rapi sedikit antara busa dan kain pelapis dan panas,agak beranta di bagi dalam kurang rapi sedikit antara busa dan kain lap dan panas,"[agak, beranta, di, bagi, dalam, kurang, rapi, sedikit, antara, busa, dan, kain, lap, dan, panas]"
1,Otomotif,"Sukses terus seller, Terima kasih pak 🙏💕kurir",sukses terus seller terima kasih pak kurir,sukses terus seller terima kasih pak kurir,"[sukses, terus, seller, terima, kasih, pak, kurir]"
2,Makanan,Enak empuk\nPasti sy akan order lg,enak empuk\npasti sy akan order lg,enak empuk pasti saya akan order lagi,"[enak, empuk, pasti, saya, akan, order, lagi]"
3,Kecantikan,"Gilaaa sih ini itungan jam udah sampe aja,thanks olay👍🏻👍🏻\nPacking super super rapi,discount nya juga lumayaan😊😊",gila sih ini itungan jam udah sampe ajathanks olay\npacking super super rapidiscount nya juga lumayaan,gila sih ini hitung jam sudah sampai ajathanks olay packing super super rapidiscount nya juga lumayaan,"[gila, sih, ini, hitung, jam, sudah, sampai, ajathanks, olay, packing, super, super, rapidiscount, nya, juga, lumayaan]"
4,Elektronik,Sesuai pesanan. Mantap. Moga awet. Makasih semuanya. Belum dicoba,sesuai pesanan mantap moga awet makasih semuanya belum dicoba,sesuai pesan mantap moga awet terima kasih semua belum coba,"[sesuai, pesan, mantap, moga, awet, terima, kasih, semua, belum, coba]"
...,...,...,...,...,...
9652,Makanan,Rasa nya lumayan enak gurih,rasa nya lumayan enak gurih,rasa nya lumayan enak gurih,"[rasa, nya, lumayan, enak, gurih]"
9653,Kecantikan,mantaaaaaap abis olay ni cocok banget buat mamah aquuuuuwwwwwwwww mantap deh pokoknya,mantap abis olay ni cocok banget buat mamah aquw mantap deh pokoknya,mantap habis olay ini cocok banget buat mamah aquw mantap deh pokok,"[mantap, habis, olay, ini, cocok, banget, buat, mamah, aquw, mantap, deh, pokok]"
9654,Otomotif,"Sangat KW, kaya helm yang 50k an 🫠 ditambah pengirimannya lama syekali ..\nSemoga ini jdi bahan evaluasi 🙏",sangat kw kaya helm yang 50k an ditambah pengirimannya lama syekali \nsemoga ini jdi bahan evaluasi,sangat imitasi kaya helm yang 50k an tambah kirim lama syekali moga ini jadi bahan evaluasi,"[sangat, imitasi, kaya, helm, yang, 50k, an, tambah, kirim, lama, syekali, moga, ini, jadi, bahan, evaluasi]"
9655,Makanan,"Terima kasih barang sudah diterima dengan baik, mantap okkkk👍❤️",terima kasih barang sudah diterima dengan baik mantap ok,terima kasih barang sudah terima dengan baik mantap ok,"[terima, kasih, barang, sudah, terima, dengan, baik, mantap, ok]"
9656,Kecantikan,Utk ke-3 kali..yg ini cepet response & pengirimannya. Packaging juga aman,utk ke3 kaliyg ini cepet response pengirimannya packaging juga aman,untuk ke3 kaliyg ini cepat response kirim packaging juga aman,"[untuk, ke3, kaliyg, ini, cepat, response, kirim, packaging, juga, aman]"

# **3. Feature Extraction**

# **4. Modeling**

# **5. Comparison Model**